export enum JobName {
  SEND_RESPONSE = "SEND_RESPONSE",
  CHECK_STATUS = "CHECK_STATUS",
  STORE_SCHEDULE = "STORE_SCHEDULE",
  CLEAR_SCHEDULE = "CLEAR_SCHEDULE",
  STORE_AUTH = "STORE_AUTH",
  LOGOUT = "LOGOUT"
}
