import { timeZonesNames } from "@vvo/tzdb";
import fs from "fs";
import path from "path";
import url from "url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const typeFilePath = path.resolve(__dirname, "..", "src", "type", "timezone.generated.type.ts");

const codeString = [
  "// This file is generated by script/generate-timezone-names-type.ts.",
  "// !!! DO NOT EDIT THIS FILE DIRECTLY !!!",
  "",
  "/**",
  " * All supported timezone names. This variable is generated by `script/generate-timezone-names-type.ts`.",
  " */",
  "export enum TimezoneName {",
  timeZonesNames
    .map((name) => `  ${name.replace(/[/]/g, "__").replace(/[-]/g, "_")} = "${name}"`)
    .join(",\n"),
  "}"
].join("\n");

fs.rmSync(typeFilePath, { force: true });
fs.writeFileSync(typeFilePath, `${codeString}\n`, { encoding: "utf8" });
console.log(`Written to timezone type file at ${typeFilePath}`);
